modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/RhettL/RhettJS/issues"

[[mods]]
modId = "rhettjs"
version = "${mod_version}"
displayName = "RhettJS"
updateJSONURL = "https://github.com/RhettL/RhettJS/releases/latest"
displayURL = "https://github.com/RhettL/RhettJS"
logoFile = "logo.png"
credits = "Implementation by Claude Code"
authors = "Rhett"
description = '''
JavaScript scripting engine for Minecraft servers
'''

[[mixins]]
config = "rhettjs-neoforge.mixins.json"

[[dependencies.rhettjs]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rhettjs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rhettjs]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "NONE"
side = "BOTH"
